---
- name: Deploy reverse proxy server
  hosts: reverse_proxy_servers
  remote_user: campbelljlowman
  vars:
    ghcr_username: "campbelljlowman"
    ghcr_password: "{{ lookup('env','GITHUB_ACCESS_TOKEN') }}"


  tasks:
    - name: Login to container repository
      community.docker.docker_login:
        registry_url: ghcr.io
        username: "{{ ghcr_username }}"
        password: "{{ ghcr_password }}"

    - name: Ensure latest version of reverse proxy image is running
      community.docker.docker_container:
        image: ghcr.io/campbelljlowman/fazool-reverse-proxy:0.1.0
        name: fazool-reverse-proxy
        pull: true
        state: started
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /etc/letsencrypt:/etc/letsencrypt
          
    - name: Log out of container repository
      community.docker.docker_login:
        state: absent
