---
- name: Deploy UI server
  hosts: ui_servers
  remote_user: campbelljlowman
  vars:
    ghcr_username: "campbelljlowman"
    ghcr_password: "{{ lookup('env','GITHUB_ACCESS_TOKEN') }}"


  tasks:
    - name: Login to container repository
      community.docker.docker_login:
        registry_url: ghcr.io
        username: "{{ ghcr_username }}"
        password: "{{ ghcr_password }}"

    - name: Ensure latest version of UI image is running
      community.docker.docker_container:
        image: ghcr.io/campbelljlowman/fazool-ui:0.1.0
        name: fazool-ui
        pull: true
        state: started
        ports:
          - "5173:80"

    - name: Log out of container repository
      community.docker.docker_login:
        state: absent
